package modelo;
// Generated 14-ene-2021 21:40:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private int idCliente;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private String nifnie;
     private String telefono;
     private Set propiedadeses = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(int idCliente, String nombre, String apellido1, String apellido2, String nifnie, String telefono) {
        this.idCliente = idCliente;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.nifnie = nifnie;
        this.telefono = telefono;
    }
    public Clientes(int idCliente, String nombre, String apellido1, String apellido2, String nifnie, String telefono, Set propiedadeses) {
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.nifnie = nifnie;
       this.telefono = telefono;
       this.propiedadeses = propiedadeses;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getNifnie() {
        return this.nifnie;
    }
    
    public void setNifnie(String nifnie) {
        this.nifnie = nifnie;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getPropiedadeses() {
        return this.propiedadeses;
    }
    
    public void setPropiedadeses(Set propiedadeses) {
        this.propiedadeses = propiedadeses;
    }




}


