package modelo;
// Generated 14-ene-2021 21:40:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleadobbdd generated by hbm2java
 */
public class Empleadobbdd  implements java.io.Serializable {


     private int idEmpleado;
     private Categorias categorias;
     private Usuarios usuarios;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private String nifnie;
     private String email;
     private Set propiedadeses = new HashSet(0);

    public Empleadobbdd() {
    }

	
    public Empleadobbdd(int idEmpleado, Categorias categorias, Usuarios usuarios, String nombre, String apellido1, String apellido2, String nifnie, String email) {
        this.idEmpleado = idEmpleado;
        this.categorias = categorias;
        this.usuarios = usuarios;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.nifnie = nifnie;
        this.email = email;
    }
    public Empleadobbdd(int idEmpleado, Categorias categorias, Usuarios usuarios, String nombre, String apellido1, String apellido2, String nifnie, String email, Set propiedadeses) {
       this.idEmpleado = idEmpleado;
       this.categorias = categorias;
       this.usuarios = usuarios;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.nifnie = nifnie;
       this.email = email;
       this.propiedadeses = propiedadeses;
    }
   
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getNifnie() {
        return this.nifnie;
    }
    
    public void setNifnie(String nifnie) {
        this.nifnie = nifnie;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getPropiedadeses() {
        return this.propiedadeses;
    }
    
    public void setPropiedadeses(Set propiedadeses) {
        this.propiedadeses = propiedadeses;
    }




}


