package modelo;
// Generated 09-ene-2021 12:44:28 by Hibernate Tools 4.3.1



/**
 * Propiedades generated by hbm2java
 */
public class Propiedades  implements java.io.Serializable {


     private int idPropiedad;
     private String nombre;
     private float precio;
     private String ubicacion;
     private Float tamanio;
     private String tipoPropiedad;

    public Propiedades() {
    }

	
    public Propiedades(int idPropiedad, String nombre, float precio, String ubicacion) {
        this.idPropiedad = idPropiedad;
        this.nombre = nombre;
        this.precio = precio;
        this.ubicacion = ubicacion;
    }
    public Propiedades(int idPropiedad, String nombre, float precio, String ubicacion, Float tamanio, String tipoPropiedad) {
       this.idPropiedad = idPropiedad;
       this.nombre = nombre;
       this.precio = precio;
       this.ubicacion = ubicacion;
       this.tamanio = tamanio;
       this.tipoPropiedad = tipoPropiedad;
    }
   
    public int getIdPropiedad() {
        return this.idPropiedad;
    }
    
    public void setIdPropiedad(int idPropiedad) {
        this.idPropiedad = idPropiedad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public Float getTamanio() {
        return this.tamanio;
    }
    
    public void setTamanio(Float tamanio) {
        this.tamanio = tamanio;
    }
    public String getTipoPropiedad() {
        return this.tipoPropiedad;
    }
    
    public void setTipoPropiedad(String tipoPropiedad) {
        this.tipoPropiedad = tipoPropiedad;
    }




}


