package modelo;
// Generated 14-ene-2021 21:40:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String idUsuario;
     private String contrasenia;
     private Set empleadobbdds = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(String idUsuario, String contrasenia) {
        this.idUsuario = idUsuario;
        this.contrasenia = contrasenia;
    }
    public Usuarios(String idUsuario, String contrasenia, Set empleadobbdds) {
       this.idUsuario = idUsuario;
       this.contrasenia = contrasenia;
       this.empleadobbdds = empleadobbdds;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Set getEmpleadobbdds() {
        return this.empleadobbdds;
    }
    
    public void setEmpleadobbdds(Set empleadobbdds) {
        this.empleadobbdds = empleadobbdds;
    }




}


